import {
  Activity,
  HeartPulse,
  Pill,
  Stethoscope,
  Microscope,
  FileText,
  ScanHeart,
  FolderOpen,
} from 'lucide-react'

export const DEPARTMENTS = [
  {
    id: 'projetos-gerais',
    name: 'Projetos Gerais',
    description: 'Projetos transversais e inovação institucional.',
    icon: FolderOpen,
    modelsActive: 5,
    color: 'bg-primary/10 text-primary',
  },
  {
    id: 'escala-colaboradores',
    name: 'Escala de Colaboradores',
    description: 'Gestão da escala de colaboradores do hub.',
    icon: FolderOpen,
    modelsActive: 0,
    color: 'bg-primary/10 text-primary',
    isHidden: true,
  },
  {
    id: 'radiologia',
    name: 'Radiologia e Diagnóstico',
    description: 'Modelos de IA para análise de imagens e laudos.',
    icon: ScanHeart,
    modelsActive: 4,
    color: 'bg-primary/10 text-primary',
  },
  {
    id: 'enfermagem',
    name: 'Enfermagem',
    description: 'Assistência à beira de leito e triagem de pacientes.',
    icon: Activity,
    modelsActive: 2,
    color: 'bg-primary/10 text-primary',
  },
  {
    id: 'farmacia',
    name: 'Farmácia Clínica',
    description: 'Interações medicamentosas e farmacovigilância.',
    icon: Pill,
    modelsActive: 3,
    color: 'bg-primary/10 text-primary',
  },
]

export const TOOLS = [
  {
    id: 'analise-dados-gerais',
    departmentId: 'projetos-gerais',
    name: 'Análise de Dados Institucionais',
    status: 'Ativo',
    model: 'GPT-4o',
    description: 'Assistente para análise de métricas gerais e geração de relatórios transversais.',
    usageData: [
      { day: 'Seg', calls: 80 },
      { day: 'Ter', calls: 95 },
      { day: 'Qua', calls: 110 },
      { day: 'Qui', calls: 105 },
      { day: 'Sex', calls: 130 },
      { day: 'Sab', calls: 40 },
      { day: 'Dom', calls: 35 },
    ],
  },
  {
    id: 'escala-colaboradores-tool',
    departmentId: 'projetos-gerais',
    name: 'Escala de Colaboradores',
    status: 'Ativo',
    model: 'Sistema',
    description: 'Interface de gestão da escala de colaboradores do hub.',
    path: '/department/escala-colaboradores',
    usageData: [
      { day: 'Seg', calls: 10 },
      { day: 'Ter', calls: 12 },
      { day: 'Qua', calls: 8 },
      { day: 'Qui', calls: 15 },
      { day: 'Sex', calls: 20 },
      { day: 'Sab', calls: 5 },
      { day: 'Dom', calls: 2 },
    ],
  },
  {
    id: 'assistente-laudos',
    departmentId: 'radiologia',
    name: 'Assistente de Laudos (Raio-X/TC)',
    status: 'Ativo',
    model: 'Claude 3.5 Sonnet',
    description: 'Auxilia na estruturação e revisão de laudos radiológicos preliminares.',
    usageData: [
      { day: 'Seg', calls: 120 },
      { day: 'Ter', calls: 150 },
      { day: 'Qua', calls: 180 },
      { day: 'Qui', calls: 140 },
      { day: 'Sex', calls: 200 },
      { day: 'Sab', calls: 90 },
      { day: 'Dom', calls: 70 },
    ],
  },
  {
    id: 'analise-interacao',
    departmentId: 'farmacia',
    name: 'Análise de Interações',
    status: 'Ativo',
    model: 'GPT-4o',
    description: 'Verifica riscos de interações medicamentosas complexas em prescrições.',
    usageData: [
      { day: 'Seg', calls: 40 },
      { day: 'Ter', calls: 60 },
      { day: 'Qua', calls: 85 },
      { day: 'Qui', calls: 70 },
      { day: 'Sex', calls: 90 },
      { day: 'Sab', calls: 30 },
      { day: 'Dom', calls: 25 },
    ],
  },
  {
    id: 'triagem-inteligente',
    departmentId: 'enfermagem',
    name: 'Triagem Inteligente',
    status: 'Em Homologação',
    model: 'Llama 3',
    description: 'Sugere classificação de risco baseada em sintomas relatados.',
    usageData: [
      { day: 'Seg', calls: 10 },
      { day: 'Ter', calls: 15 },
      { day: 'Qua', calls: 20 },
      { day: 'Qui', calls: 18 },
      { day: 'Sex', calls: 25 },
      { day: 'Sab', calls: 30 },
      { day: 'Dom', calls: 22 },
    ],
  },
]

export const RECENT_HISTORY = [
  {
    id: '1',
    date: '2023-10-27T14:30:00Z',
    tool: 'Assistente de Laudos',
    summary: 'TC Crânio - Paciente 45a trauma...',
  },
  {
    id: '2',
    date: '2023-10-27T10:15:00Z',
    tool: 'Análise de Interações',
    summary: 'Varfarina + Amiodarona consulta...',
  },
  {
    id: '3',
    date: '2023-10-26T16:45:00Z',
    tool: 'Assistente de Laudos',
    summary: 'RX Tórax - Suspeita pneumonia...',
  },
]

export const AUDIT_LOGS = [
  {
    id: 'LOG-001',
    timestamp: '2023-10-27 14:30:22',
    user: 'Dr. Carlos Silva',
    role: 'Médico',
    department: 'Radiologia',
    action: 'Geração de Laudo',
    tokens: 1250,
  },
  {
    id: 'LOG-002',
    timestamp: '2023-10-27 14:15:10',
    user: 'Enf. Marina Costa',
    role: 'Enfermeiro Sênior',
    department: 'Enfermagem',
    action: 'Consulta Triagem',
    tokens: 450,
  },
  {
    id: 'LOG-003',
    timestamp: '2023-10-27 13:50:05',
    user: 'Farm. Roberto Dias',
    role: 'Farmacêutico',
    department: 'Farmácia',
    action: 'Análise Prescrição',
    tokens: 890,
  },
  {
    id: 'LOG-004',
    timestamp: '2023-10-27 11:20:00',
    user: 'Dra. Ana Paula',
    role: 'Médico',
    department: 'Projetos Gerais',
    action: 'Revisão Protocolo',
    tokens: 2100,
  },
]

export const USERS = [
  {
    id: 'U1',
    name: 'Dr. Carlos Silva',
    email: 'carlos.silva@bp.org.br',
    role: 'Operador',
    department: 'Radiologia',
  },
  {
    id: 'U2',
    name: 'Enf. Marina Costa',
    email: 'marina.costa@bp.org.br',
    role: 'Gerente',
    department: 'Enfermagem',
  },
  { id: 'U3', name: 'Admin TI', email: 'admin.ti@bp.org.br', role: 'Admin', department: 'TI' },
]
