import { describe, it, expect, vi } from 'vitest'
import { BPSCS_LOGO_BASE64 } from '@/utils/bpscsLogo'
import {
  exportScalePdf,
  exportAutoGenerateCalendarPdf,
  exportAutoGenerateDailyListPdf,
} from '@/utils/scalePdfExport'
import { exportCollaboratorsToPdf } from '@/utils/staffReportExport'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

describe('Logotipo institucional BPSCS e exportadores de PDF', () => {
  it('BPSCS_LOGO_BASE64 possui formato data:image/png;base64, decodifica com assinatura PNG válida e tem tamanho consistente', () => {
    expect(BPSCS_LOGO_BASE64).toMatch(/^data:image\/png;base64,/)

    const rawBase64 = BPSCS_LOGO_BASE64.replace(/^data:image\/png;base64,/, '')
    expect(rawBase64.length).toBeGreaterThan(1000)

    // Decodifica base64 para bytes
    const binaryStr = atob(rawBase64)
    const bytes = new Uint8Array(binaryStr.length)
    for (let i = 0; i < binaryStr.length; i++) {
      bytes[i] = binaryStr.charCodeAt(i)
    }

    // Assinatura PNG padrão: 137 80 78 71 13 10 26 10 (\x89PNG\r\n\x1a\n)
    const pngSignature = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]
    for (let i = 0; i < pngSignature.length; i++) {
      expect(bytes[i]).toBe(pngSignature[i])
    }
  })

  it('Os 4 exportadores de PDF chamam addImage com (BPSCS_LOGO_BASE64, "PNG", 263, 6, 24, 18)', () => {
    const addImageCalls: any[][] = []

    vi.spyOn(jsPDF.prototype, 'save').mockImplementation(() => undefined as any)
    vi.spyOn(jsPDF.prototype, 'addImage').mockImplementation((...args: any[]) => {
      addImageCalls.push(args)
      return undefined as any
    })

    // Garante execução de didDrawPage em cada autoTable call
    vi.mocked(autoTable).mockImplementation((_doc, options: any) => {
      if (typeof options?.didDrawPage === 'function') {
        options.didDrawPage()
      }
      return options
    })

    // 1. Relatório Geral de Colaboradores (staffReportExport)
    addImageCalls.length = 0
    exportCollaboratorsToPdf([
      {
        id: '1',
        name: 'Colaborador Teste',
        professionalId: '12345-SP',
        role: 'Enfermeiro',
        sector: 'UTI',
        contractType: 'CLT',
        monthlyHourLimit: '180h',
        shiftType: '12x36',
        shiftParity: 'Equipe 1',
        cycleStartDate: '01/10/2026',
        status: 'Ativo',
        vacationStatus: 'Sem férias',
        vacationPeriod: '-',
        rulesCount: 0,
        rulesList: '-',
        createdAt: '01/01/2026',
        updatedAt: '01/01/2026',
      },
    ])
    expect(addImageCalls.length).toBeGreaterThanOrEqual(1)
    expect(addImageCalls[0]).toEqual([BPSCS_LOGO_BASE64, 'PNG', 263, 6, 24, 18])

    // 2. Grade de Plantões do Planejador (scalePdfExport - exportScalePdf)
    addImageCalls.length = 0
    exportScalePdf({
      title: 'Escala Planejador',
      sectorName: 'UTI',
      cycleStart: '2026-10-01',
      cycleEnd: '2026-10-31',
      staffNames: { 'staff-1': 'Colaborador 1' },
      staffRows: ['staff-1'],
      dateHeaders: ['2026-10-01'],
      cellMap: { 'staff-1': { '2026-10-01': { type: 'day' } } },
      weekendOffMap: new Map(),
    })
    expect(addImageCalls.length).toBeGreaterThanOrEqual(1)
    expect(addImageCalls[0]).toEqual([BPSCS_LOGO_BASE64, 'PNG', 263, 6, 24, 18])

    // 3. Calendário Mensal da IA (scalePdfExport - exportAutoGenerateCalendarPdf)
    addImageCalls.length = 0
    exportAutoGenerateCalendarPdf({
      title: 'Calendário IA',
      sectorName: 'UTI',
      cycleName: 'Ciclo Out/2026',
      cycleStart: '2026-10-01',
      cycleEnd: '2026-10-31',
      days: [{ date: new Date(2026, 9, 1), key: '2026-10-01', dayOfWeek: 4 }],
      shifts: [],
      contracts: [],
      staffProfiles: [],
      weekendOffMap: new Map(),
    })
    expect(addImageCalls.length).toBeGreaterThanOrEqual(1)
    expect(addImageCalls[0]).toEqual([BPSCS_LOGO_BASE64, 'PNG', 263, 6, 24, 18])

    // 4. Lista por Dia com COREN da IA (scalePdfExport - exportAutoGenerateDailyListPdf)
    addImageCalls.length = 0
    exportAutoGenerateDailyListPdf({
      title: 'Lista Diária IA',
      sectorName: 'UTI',
      cycleName: 'Ciclo Out/2026',
      cycleStart: '2026-10-01',
      cycleEnd: '2026-10-31',
      draftShifts: [],
      contracts: [],
      staffProfiles: [],
    })
    expect(addImageCalls.length).toBeGreaterThanOrEqual(1)
    expect(addImageCalls[0]).toEqual([BPSCS_LOGO_BASE64, 'PNG', 263, 6, 24, 18])
  })
})
