import { describe, it, expect, vi, beforeEach } from 'vitest'
import {
  exportScalePdf,
  exportAutoGenerateDailyListPdf,
  exportAutoGenerateCalendarPdf,
  formatSafeFilename,
  type ShiftSlot,
  type ExportScalePdfParams,
  type ExportAutoGenerateDailyListPdfParams,
  type ExportAutoGenerateCalendarPdfParams,
} from '../src/utils/scalePdfExport'

// Mock de jsPDF e jspdf-autotable para inspecionar geração e salvamento
const mockSave = vi.fn()
const mockText = vi.fn()
const mockSetFont = vi.fn()
const mockSetFontSize = vi.fn()
const mockSetTextColor = vi.fn()
const mockSetProperties = vi.fn()
const mockAddPage = vi.fn()
const mockSetPage = vi.fn()
const mockGetNumberOfPages = vi.fn().mockReturnValue(1)
let lastAutoTableArgs: any = null
let allAutoTableCalls: any[] = []

vi.mock('jspdf', () => {
  return {
    jsPDF: vi.fn().mockImplementation(() => ({
      save: mockSave,
      text: mockText,
      setFont: mockSetFont,
      setFontSize: mockSetFontSize,
      setTextColor: mockSetTextColor,
      setProperties: mockSetProperties,
      addPage: mockAddPage,
      setPage: mockSetPage,
      getNumberOfPages: mockGetNumberOfPages,
      internal: {
        pageSize: {
          getWidth: () => 297,
          getHeight: () => 210,
        },
      },
    })),
  }
})

vi.mock('jspdf-autotable', () => {
  return {
    default: vi.fn((_doc, options) => {
      lastAutoTableArgs = options
      allAutoTableCalls.push(options)
      if (options.didDrawPage) {
        options.didDrawPage()
      }
      return options
    }),
  }
})

describe('scalePdfExport Suite (ScalePlanner & AutoGenerate IA)', () => {
  beforeEach(() => {
    mockSave.mockClear()
    mockText.mockClear()
    mockSetProperties.mockClear()
    lastAutoTableArgs = null
    allAutoTableCalls = []
  })

  const staffNames: Record<string, string> = {
    user_1: 'Colaborador Ficticio Alfa',
    user_2: 'Colaborador Ficticio Beta',
    user_3: 'Colaborador Ficticio Gama',
  }

  const staffRows = ['user_1', 'user_2', 'user_3']

  const dateHeaders = [
    '2026-10-01',
    '2026-10-02',
    '2026-10-03', // Sábado
    '2026-10-04', // Domingo
    '2026-10-05',
  ]

  const cellMap: Record<string, Record<string, ShiftSlot>> = {
    user_1: {
      '2026-10-01': { type: 'day', start: '07:00', end: '19:00' },
      '2026-10-02': { type: 'night', start: '19:00', end: '07:00' },
    },
    user_2: {
      '2026-10-01': { type: 'night', start: '19:00', end: '07:00' },
      '2026-10-05': { type: 'day', start: '07:00', end: '19:00' },
    },
    user_3: {
      '2026-10-02': { type: 'day', start: '07:00', end: '19:00' },
    },
  }

  const weekendOffMap = new Map<string, Set<string>>()
  weekendOffMap.set('user_1', new Set(['2026-10-03', '2026-10-04']))

  describe('ScalePlanner PDF Export (scalePdfExport)', () => {
    it('Nome do arquivo segue o padrão escala-{YYYY}-{MM}.pdf', () => {
      expect(formatSafeFilename('2026-10-01')).toBe('escala-2026-10.pdf')
      expect(formatSafeFilename('2025-05-15')).toBe('escala-2025-05.pdf')

      const currentName = formatSafeFilename()
      expect(currentName).toMatch(/^escala-\d{4}-\d{2}\.pdf$/)
    })

    it('Chama exportScalePdf e invoca jsPDF.save com nome correto e propriedades', () => {
      const data: ExportScalePdfParams = {
        title: 'Escala de Plantões',
        sectorName: 'UTI Ficticia',
        cycleStart: '2026-10-01',
        cycleEnd: '2026-10-31',
        staffNames,
        staffRows,
        dateHeaders,
        cellMap,
        weekendOffMap,
      }

      const filename = exportScalePdf(data)

      expect(filename).toBe('escala-2026-10.pdf')
      expect(mockSave).toHaveBeenCalledWith('escala-2026-10.pdf')
      expect(lastAutoTableArgs).toBeDefined()
    })

    it('exportScalePdf destaca "FOLGA" com cor laranja nas células de folga de fim de semana', () => {
      exportScalePdf({
        title: 'Escala de Plantões',
        sectorName: 'UTI Ficticia',
        cycleStart: '2026-10-01',
        cycleEnd: '2026-10-31',
        staffNames,
        staffRows,
        dateHeaders,
        cellMap,
        weekendOffMap,
      })

      const body = lastAutoTableArgs.body
      const user1Sat = body[0][3]
      const user1Sun = body[0][4]

      expect(user1Sat.content).toBe('FOLGA')
      expect(user1Sat.styles.fillColor).toEqual([255, 243, 224])
      expect(user1Sat.styles.textColor).toEqual([194, 65, 12])
      expect(user1Sat.styles.fontStyle).toBe('bold')

      expect(user1Sun.content).toBe('FOLGA')
      expect(user1Sun.styles.fillColor).toEqual([255, 243, 224])
    })
  })

  describe('AutoGenerate IA: 1) Relatório Lista por Dia (exportAutoGenerateDailyListPdf)', () => {
    const dummyStaffProfiles = [
      {
        id: 'prof-1',
        name: 'Enfermeiro Teste Um',
        professional_id: '12345-SP',
      },
      {
        id: 'prof-2',
        name: 'Tecnico Teste Dois',
        professional_id: null, // Sem COREN
      },
    ]

    const dummyContracts = [
      {
        staff_profile: 'prof-1',
        expand: {
          shift_type: { name: '12x36 Diurno', code: '12D' },
        },
      },
      {
        staff_profile: 'prof-2',
        expand: {
          shift_type: { name: '12x36 Noturno', code: '12N' },
        },
      },
    ]

    const dummyDraftShifts = [
      {
        id: 's-1',
        staff_profile: 'prof-1',
        start_time: '2026-10-01 07:00:00.000Z',
        end_time: '2026-10-01 19:00:00.000Z',
        sector: 'sec-1',
        expand: {
          staff_profile: dummyStaffProfiles[0],
          sector: { name: 'UTI Geral Teste' },
        },
      },
      {
        id: 's-2',
        staff_profile: 'prof-2',
        start_time: '2026-10-01 19:00:00.000Z',
        end_time: '2026-10-02 07:00:00.000Z',
        sector: 'sec-1',
        expand: {
          staff_profile: dummyStaffProfiles[1],
          sector: { name: 'UTI Geral Teste' },
        },
      },
    ]

    it('Gera relatório no formato Lista por dia incluindo coluna COREN e dados completos', () => {
      const params: ExportAutoGenerateDailyListPdfParams = {
        title: 'Escala de Plantões — Rascunho',
        sectorName: 'UTI Geral Teste',
        cycleName: 'Ciclo Outubro 2026',
        cycleStart: '2026-10-01',
        cycleEnd: '2026-10-31',
        draftShifts: dummyDraftShifts,
        contracts: dummyContracts,
        staffProfiles: dummyStaffProfiles,
      }

      const filename = exportAutoGenerateDailyListPdf(params)

      expect(filename).toBe('escala-2026-10.pdf')
      expect(mockSave).toHaveBeenCalledWith('escala-2026-10.pdf')
      expect(lastAutoTableArgs).toBeDefined()

      // Validação das colunas do cabeçalho
      const head = lastAutoTableArgs.head[0]
      expect(head).toEqual([
        'Data',
        'Dia',
        'Colaborador',
        'COREN',
        'Tipo',
        'Início',
        'Fim',
        'Setor',
      ])

      // Validação das linhas com COREN real e fallback
      const body = lastAutoTableArgs.body
      expect(body.length).toBe(2)

      // Linha 1: Enfermeiro Teste Um com COREN real
      const row1 = body[0]
      expect(row1[0]).toBe('01/10/2026')
      expect(row1[1]).toBe('Qui')
      expect(row1[2]).toBe('Enfermeiro Teste Um')
      expect(row1[3]).toBe('COREN 12345-SP')
      expect(row1[4]).toBe('12x36 Diurno')
      expect(row1[5]).toBe('07:00')
      expect(row1[6]).toBe('19:00')
      expect(row1[7]).toBe('UTI Geral Teste')

      // Linha 2: Tecnico Teste Dois com fallback "COREN não informado"
      const row2 = body[1]
      expect(row2[2]).toBe('Tecnico Teste Dois')
      expect(row2[3]).toBe('COREN não informado')
      expect(row2[4]).toBe('12x36 Noturno')
      expect(row2[5]).toBe('19:00')
      expect(row2[6]).toBe('07:00')
    })
  })

  describe('AutoGenerate IA: 2) Relatório Calendário Mensal (exportAutoGenerateCalendarPdf)', () => {
    const dummyStaffProfiles = [
      {
        id: 'prof-1',
        name: 'Plantonista Alpha Silva',
        professional_id: '54321',
        default_sector: 'sec-1',
      },
      {
        id: 'prof-2',
        name: 'Plantonista Beta Santos',
        professional_id: '',
        default_sector: 'sec-1',
      },
    ]

    const dummyContracts = [
      {
        staff_profile: 'prof-1',
        expand: {
          shift_type: { name: 'Diurno', start_time: '07:00', end_time: '19:00' },
        },
      },
      {
        staff_profile: 'prof-2',
        expand: {
          shift_type: { name: 'Noturno', start_time: '19:00', end_time: '07:00' },
        },
      },
    ]

    const days = [
      { date: new Date(2026, 9, 1), key: '2026-10-01', dayOfWeek: 4 }, // Quinta
      { date: new Date(2026, 9, 2), key: '2026-10-02', dayOfWeek: 5 }, // Sexta
      { date: new Date(2026, 9, 3), key: '2026-10-03', dayOfWeek: 6 }, // Sábado
      { date: new Date(2026, 9, 4), key: '2026-10-04', dayOfWeek: 0 }, // Domingo
    ]

    const dummyShifts = [
      {
        id: 's-1',
        staff_profile: 'prof-1',
        start_time: '2026-10-01 07:00:00.000Z',
        end_time: '2026-10-01 19:00:00.000Z',
        sector: 'sec-1',
        expand: { staff_profile: dummyStaffProfiles[0] },
      },
      {
        id: 's-2',
        staff_profile: 'prof-2',
        start_time: '2026-10-01 19:00:00.000Z',
        end_time: '2026-10-02 07:00:00.000Z',
        sector: 'sec-1',
        expand: { staff_profile: dummyStaffProfiles[1] },
      },
    ]

    const weekendOffMap = new Map<string, Set<string>>()
    // prof-1 tem folga de fim de semana em 2026-10-03 (sábado)
    weekendOffMap.set('prof-1', new Set(['2026-10-03']))

    it('Gera grade de calendário mensal com D/N + COREN e destaque de Folga Fim de Semana', () => {
      const params: ExportAutoGenerateCalendarPdfParams = {
        title: 'Escala de Plantões — Calendário',
        sectorName: 'UTI Adulto Teste',
        cycleName: 'Ciclo Outubro 2026',
        cycleStart: '2026-10-01',
        cycleEnd: '2026-10-31',
        days,
        shifts: dummyShifts,
        contracts: dummyContracts,
        staffProfiles: dummyStaffProfiles,
        weekendOffMap,
        selectedSectorId: 'sec-1',
      }

      const filename = exportAutoGenerateCalendarPdf(params)

      expect(filename).toBe('escala-2026-10.pdf')
      expect(mockSave).toHaveBeenCalledWith('escala-2026-10.pdf')
      expect(lastAutoTableArgs).toBeDefined()

      // Validação das células
      const body = lastAutoTableArgs.body
      expect(body.length).toBeGreaterThanOrEqual(1)

      const week1 = body[0]
      // Dia 1 (Quinta - índice 0 na semana): plantão diurno de prof-1 e noturno de prof-2
      const day1Cell = week1[0]
      expect(day1Cell.content).toContain('[ 01/10 ]')
      expect(day1Cell.content).toContain('• Plantonista Alpha Silva')
      expect(day1Cell.content).toContain('D • COREN 54321')
      expect(day1Cell.content).toContain('• Plantonista Beta Santos')
      expect(day1Cell.content).toContain('N • COREN não informado')

      // Dia 3 (Sábado - índice 2 na semana): Folga Fim de Semana para prof-1
      const satCell = week1[2]
      expect(satCell.content).toContain('[ 03/10 ]')
      expect(satCell.content).toContain('• Plantonista Alpha Silva')
      expect(satCell.content).toContain('Folga Fim de Semana')
    })
  })
})
